# change prefix key to Ctrl-a; like GNU Screen
# unbind-key C-b
# set-option -g prefix C-a
# goto last used window
bind-key C-b last-window
bind-key b send-prefix

# Make Ctrl+arrows work
set-option -g xterm-keys on
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

bind-key | split-window -h
bind-key - split-window -v

# Allow mouse to select which pane to use
set -g mouse-select-pane on
# set -g mode-mouse on # toll zum Selektieren, überschreibt eine Funktion des Terminals
# set -g mouse-resize-pane on # komische Artefakte
set -g mouse-select-window on

set -g history-limit 30000
bind-key R  source-file ~/.tmux.conf \; display "Reloaded!"

set -g status-justify centre           # center window list for clarity
set-option -g status-position bottom    # position the status bar at top of screen

# visual notification of activity in other windows
# setw -g monitor-activity on
# set -g visual-activity on

# set color for status bar
set-option -g status-bg colour235 #base02
set-option -g status-fg yellow #yellow
# set-option -g status-attr dim 

# set window list colors - red for active and cyan for inactive
set-window-option -g window-status-fg yellow  #base0
set-window-option -g window-status-bg colour236 
set-window-option -g window-status-attr dim
set-window-option -g window-status-current-fg colour235 #base02 ####brightred #orange
set-window-option -g window-status-current-bg yellow 
set-window-option -g window-status-current-attr bright

# UTF-8 character support in the status bar
set-option -g status-utf8 on
set-option -g status-left-length 40
set-option -g status-left "#H %R"
set-option -g status-right "%a. %d.%B"

# Time messages remain in the status bar. Lower this number
# if this is too distracting.
set-option -g display-time 4000

# http://tangledhelix.com/blog/2012/07/16/tmux-and-mouse-mode/
# Toggle mouse on
bind-key m \
  set-option -g mode-mouse on \;\
  set-option -g mouse-resize-pane on \;\
  display-message 'Mouse: ON'

# Toggle mouse off
bind-key M \
  set-option -g mode-mouse off \;\
  set-option -g mouse-resize-pane off \;\
  display-message 'Mouse: OFF'
