Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
	Option "NaturalScrolling" "on"
	Option "TappingButtonMap" "lrm"
	Option "AccelSpeed" "1"
	Option "ClickMethod" "clickfinger"
EndSection
