#!/bin/sh

cclean() {
	docker rm $(docker ps -qa)
}

iclean() {
	docker rmi $(docker images -q -f dangling=true)
}

backup() {
	echo "---------------Scheduled backup time---------------"
	echo ""
	borg create /media/hdd/backup::$(date +%Y%m%d) /media/hdd/archive ~/src ~/Documents ~/Pictures ~/docs
	echo ""
	echo "---------------Backup done, removing old snapshots---------------"
	echo ""
	borg prune -v --list --keep-daily=7 --keep-weekly=6 --keep-monthly=12 /media/hdd/backup
	echo ""
	echo "---------------Backup done and verified!---------------"
}

create_note() {
	ID=$(date +"%Y%m%d%H%M")
	DATE=$(date +"%a %d %b %Y")
	FILE=$ID.md
	touch $FILE
	cat << EOF > $FILE
---
title: <title>
date: $DATE
id: $ID
author: Mathis Engelbart
keywords: []
---
EOF
	echo $FILE
}
