#!/bin/sh

cclean() {
	docker rm $(docker ps -qa)
}

iclean() {
	docker rmi $(docker images -q -f dangling=true)
}

backup() {
	echo "---------------Scheduled backup time---------------"
	echo ""
	borg create /media/hdd/backup::$(date +%Y%m%d) \
		/media/hdd/archive \
		~/src \
		~/Documents \
		~/Pictures \
		~/Zotero \
		~/.var/app/net.ankiweb.Anki/data/Anki2
	echo ""
	echo "---------------Backup done, removing old snapshots---------------"
	echo ""
	borg prune -v --list --keep-daily=7 --keep-weekly=6 --keep-monthly=12 /media/hdd/backup
	echo ""
	echo "---------------Backup done and verified!---------------"
}

note() {
	ID=$(date +"%Y%m%d%H%M")
	DATE=$(date +"%a %d %b %Y")
	FILE=$ID.md
	if [ -z ${1+x} ];
	then
		echo "var is unset";
	else
		echo "var is set to '$1'";
		mkdir -p $1
		FILE=$1/$FILE
	fi
	touch $FILE
	cat << EOF > $FILE
---
title: Notes
date: $DATE
id: $ID
author: Mathis Engelbart
keywords: []
---
EOF
	echo $FILE
}
