#!/bin/sh

RESET=$'\e[0m'
RED=$'\e[31;49m'
GREEN=$'\e[32;49m'
BLUE=$'\e[34:49m'

if [ -x "$(command -v git)" ]; then
	GIT_PS1_SHOWDIRTYSTATE=true
	GIT_PS1_SHOWCOLORHINTS=true

	# location of git prompt shell script on fedora
	. /usr/share/git-core/contrib/completion/git-prompt.sh
fi

PROMPT_COMMAND='__git_ps1 "\[$GREEN\]\u@\h\[$RESET\]:\[$BLUE\]\w\[$RESET\] \[$RED\]\A\[$RESET\]" "\$ "'

